steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_gcs
  - --runtime=python312
  - --region=europe-west1
  - --trigger-bucket=gs://bucketej
  - --allow-unauthenticated
  - --source=./mifuncion